### ISSUE TITLE
What is the future of Xamarin in .NET 5.0?

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/designs#132]
When .NET 5.0 is released, there are new TFMs (`net5.0-android`, `net5.0-ios`). Are these the replacement to Xamarin?
Will we still be able to make x-platform apps (use both monikers at the same time)?

Another question:
If `net5.0-windows` is used for WPF and WinForms, so what's the story of [MAUI](https://github.com/dotnet/maui)?

Too many technologies got me confused 😄

**Comment by maxkatz6** [comment]
> Are these the replacement to Xamarin?
It is Xamarin, but merged into .Net.

> what's the story of MAUI
MAUI is Xamarin Forms. And it seems it will support Windows as well without UWP. I am not sure, but it will probably use WinUI to cover both UWP and WPF/WinForms.

**Comment by Youssef1313** [comment]
> It is Xamarin, but merged into .Net.

But [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/) repo is still developing on its own. That still confuses me.

> MAUI is Xamarin Forms. And it seems it will support Windows as well without UWP. I am not sure, but it will probably use WinUI to cover both UWP and WPF/WinForms.

This is even more confusing. If MAUI is Xamarin, and Xamarin is net5.0-android and net5.0-ios. Then, what is the relation between MAUI and WPF/WinForms?

Will net5.0-android, net5.0-ios, net5.0-windows be merged later to be just maui?

The situation is really really confusing.

**Comment by Happypig375** [comment]
>But Xamarin.Forms repo is still developing on its own. That still confuses me.

Read the FAQ. Xamarin.Forms will be in maintenance-mode after version 5.
> If MAUI is Xamarin, and Xamarin is net5.0-android and net5.0-ios.

MAUI is Xamarin.Forms ≠ Xamarin. Xamarin (Classic/Native) = Xamarin.iOS, Xamarin.Android, Xamarin.Mac. 
>Then, what is the relation between MAUI and WPF/WinForms?

MAUI is cross-platform, covering iOS, Android, Windows, Linux, Mac, iPadOS, Tizen, etc.
WPF/WinForms is Windows-only.
>Will net5.0-android, net5.0-ios, net5.0-windows be merged later to be just maui?

.net5.0-windows will not become winforms/wpf/uwp. Likewise, that will not happen.

**Comment by terrajobst** [comment]
This is explained in depth in the [TFM design document](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md). The high-level summary is in [this 2-min video](https://www.youtube.com/watch?v=-kAr21i11f4).
