### ISSUE TITLE
README should be more clear about what this repo is for

### ISSUE THREAD

**Issue by svick** [dotnet/designs#6]
> The dotnet/designs repo contains designs and design proposals for .NET.

From this description, it's not clear to me at all what a "design" is.

> Create an issue requesting a new feature.

What kind of features? I'm assuming that most language design or API design discussions don't belong here, but then what does?

**Comment by MgSam** [comment]
Seems like this repo has already been abandoned. :/

**Comment by Phrohdoh** [comment]
I believe this repo is similar to the [Rust RFC](https://github.com/rust-lang/rfcs) repo which houses discussions and proposals of varying nature.

Regardless of whether what I have said is correct or not I do agree that clarity here is necessary.
