### ISSUE TITLE
Add concatenation method to int type

### ISSUE THREAD

**Issue by akmadian** [dotnet/designs#66]
I'm not sure if this is the right place for this, but I have wanted to concatenate two integers into a new int many times, and while writing an extension method really isn't that much of a pain, but I think that this feature may have a place in .NET.

Instead of this:
```csharp
int x = 1;
int y = 2;

Int.Parse(x.ToString() + y.ToString());
```

I usually use something like this:
```csharp
int x = 1;
int y = 2;

x.Concat(y); // = 12
```

This method could be written so that a collection of ints may be passed as a parameter. I imagine that this feature addition would be welcome for many people (including myself!)

**Comment by svick** [comment]
If you're suggesting adding a new method to .Net Core, then following [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md), the right place is [the corefx repository](https://github.com/dotnet/corefx).

Regarding the proposal itself: when is this operation actually useful?

**Comment by akmadian** [comment]
Thanks for pointing me towards the proper place!

As for when it's useful: I've used it in a couple of my projects and I just kinda assumed that this is relatively common, and that other people also use this in their work.
